name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - run: npm ci --legacy-peer-deps
      - uses: nrwl/nx-set-shas@v4

      - name: Start the server
        run: |
          nohup nx serve auth --configuration=development &> server.log &
          tail -f server.log

      - name: Check if server is running
        run: |
          lsof -i :3000 || echo "No server running on port 3000"

      - name: Wait for the server to be available
        run: |
          TIMEOUT=60
          until curl --silent --head --fail http://localhost:3000/api || [ $TIMEOUT -le 0 ]; do
            echo "Waiting for server to be available..."
            sleep 5
            TIMEOUT=$((TIMEOUT-5))
          done
          if [ $TIMEOUT -le 0 ]; then
            echo "Server did not start in time!"
            exit 1
          fi

      - run: npx nx affected -t lint test build
